version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/openfresh/ecs-formation
    steps:
      - checkout
      - run: make deps 
      - run: make test 
      - persist_to_workspace:
          root: .
          paths:
            - "*"

  release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/openfresh/ecs-formation
    steps:
      - attach_workspace:
          at: .
      - run: make build-all
      - run: ./release.sh
  
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build 
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

